### ISSUE TITLE
Co-debug and JavaScript exception handling

### ISSUE THREAD

**Issue by markm77** [JeringTech/Javascript.NodeJS#86] opened 2020-07-25 23:47 UTC
Hi there,

I am using JetBrains Rider to co-debug (simultaneously debug) C# and JavaScript (actually TypeScript via source maps).

Rider has a nice "Attach to Node.js/Chrome" debug config which crucially includes an option to "Reconnect  automatically". Thus I can just leave this debug config on and it always picks up calls to JavaScript from ```StaticNodeJSService.InvokeFromFileAsync()``` when ```options.NodeAndV8Options = "--inspect-brk"```. I can thus concentrate on starting and stopping C# code and watch both C# and TypeScript break points get hit which is fantastic.

So far so good.

However when I set Rider to automatically break on (caught) JavaScript exceptions, it always breaks immediately following ```StaticNodeJSService.InvokeFromFileAsync()``` with the following exception:
```
ReferenceError: Cannot access 'd' before initialization
    at [eval]:1:2103
    at Object.<anonymous> ([eval]:1:2395)
    at n ([eval]:1:124)
    at [eval]:1:923
    at [eval]:1:932
    at Script.runInThisContext (vm.js:120:20)
    at Object.runInThisContext (vm.js:311:38)
    at Object.<anonymous> ([eval]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at evalScript (internal/process/execution.js:94:25)
```
which comes from ```try{e=i._makeLong(d);``` in some code called ```[eval]``` which seems to be some kind of JavaScript wrapper. The exception is caught and perhaps the code is perfectly functioning as designed.

Also all my user code exceptions are also caught (again great in the general case - seems exceptions are effectively re-thrown in C# with nice stack trace).

Unfortunately though this means to break on JavaScript terminating exceptions in my code I need to configure Rider to stop on caught JavaScript exceptions.... including the exception in ```[eval]``` which seems to be triggered every time JavaScript is called.

I am wondering if you might therefore consider providing an option to not catch top-level (uncaught) user exceptions in JavaScript so that I can configure Rider to break on uncaught exceptions to see terminating failures in JavaScript debugging context? Obviously even I would not want this most of the time but when co-debugging it would be useful.

Also if the exception in ```[eval]``` is a bug it would make exception breaking easier if it were fixed (or designed away).

Any alternative thoughts you have would be very welcome and thanks for this tool!

BR,
Mark

**Comment by JeremyTCD** [comment] 2020-07-26 02:21
Hi Mark,

Correct me if I've misunderstood anything: You'd like to break on exceptions not caught by user code. At present, this library always catches all exceptions so this can't be done by configuring your debugger to break at uncaught exceptions. You'd like a flag to temporarily disable the library's catching of user exceptions. 

If that's it, I think it's a good idea - I agree that breaking at every caught exception can be a real pain.  

The catch-all try block is in [HttpServer.ts](https://github.com/JeringTech/Javascript.NodeJS/blob/master/src/NodeJS/Javascript/Servers/OutOfProcess/Http/HttpServer.ts#L58-L192) as seen below:

```js
function serverOnRequestListener(req, res) {
    let bodyChunks = [];
    req.
        on('data', chunk => bodyChunks.push(chunk)).
        on('end', async () => {
            try {
                // Process invocation
                ...
            } catch (error) {
                // We could try this
                if (flag) { throw error; }

                respondWithError(res, error);
            }
        });
}
```

Here I've added a line, `if (flag) { throw error; }`. I'm not sure if the debugger will break there or at the original error, I'll have to read up and experiment. Would you be willing to clone this repo, add the flag and try with your debugger? If you're down, I'm open to merging a PR for with those additions.

**Comment by markm77** [comment] 2020-07-26 13:49
Thanks @JeremyTCD for your quick and helpful response.

> You'd like a flag to temporarily disable this library's catching of user exceptions.

Yes, that's what I was looking for. And, sure, the ```[eval]``` exception was more for your info, I totally understand if this is an upstream issue and of course it may be design behaviour. Let's not worry about that here.

I'm more than happy to test your suggested fix next week. We can take it from there.

**Comment by JeremyTCD** [comment] 2020-07-26 14:12
No problem :).

> I'm more than happy to test your suggested fix next week. We can take it from there.

Okay great, go ahead and create a pull request if it works.

**Comment by markm77** [comment] 2020-08-02 15:42
Sorry, totally overwhelmed this week, will try again to test next week.

**Comment by JeremyTCD** [comment] 2020-08-02 16:40
Hey no hurry! Might have a go at it this week too.

**Comment by JeremyTCD** [comment] 2020-08-08 14:32
Hey Mark,

Was just working on a flag. Changed:

https://github.com/JeringTech/Javascript.NodeJS/blob/6732fda4ab9146a67ff9d492a3260deb9c507a1f/src/NodeJS/Javascript/Servers/OutOfProcess/Http/HttpServer.ts#L188-L190


Am using Chrome to debug. Two observations:

**Comment by markm77** [comment] 2020-08-12 17:49
Hi Jeremy,

Thanks for your efforts, appreciated. An update from me.

I cloned your repo and tried to build it using Rider but doesn't seem to build. (I uninstalled Visual Studio recently due to a conflict with Rider.) So I'll need a bit more time to solve build issues (if I can) to test.

But basically if there's no stack trace this hardly seems worth it. I wanted to try with VS Code debugger to see what happens there.

BR,
Mark

PS I also recently tried to use this project unsuccessfully with macOS and I guess it's not cross-platform.... ? Do you know if it works on Linux?

**Comment by JeremyTCD** [comment] 2020-08-13 04:48
Hey I've packaged the changes and pushed the package to a [temporary public Nuget feed](https://dev.azure.com/JeringTech/Javascript.NodeJS/_packaging?_a=feed&feed=Temp%40Local).

This means you can test the build without cloning:

1. Add "https://pkgs.dev.azure.com/JeringTech/Javascript.NodeJS/_packaging/Temp/nuget/v3/index.json" to your Nuget sources. 
Here's how you can do that in Rider: [Rider manager package sources](https://www.jetbrains.com/help/rider/Using_NuGet.html#sources).

2. Bump Jering.Javascript.NodeJS to 5.4.3-preview.0. Rider should be smart enough to find this version in the temporary feed.

3. As mentioned in the PR, set `NodeJSProcessOptions.CatchUncaughtUserErrors` to `false`. [More info on setting `NodeJSProcessOptions` values](https://github.com/JeringTech/Javascript.NodeJS#configuring-inodejsservice).

4. Try debugging, you should be able to break at uncaught user errors. You'll have full stack trace etc.

I've verified on my local machine that the above steps work with VS. Unfortunately I do not have rider, do let me know how it goes. 

Other issues:

- macOS and Linux are supported. Every version of this package is built and tested on macOS and Linux, e.g. [latest build](https://dev.azure.com/JeringTech/Javascript.NodeJS/_build/results?buildId=1010&view=results). Kindly open a separate issue with details on the errors you encountered on macOS, will be happy to look into it.

- Building using Rider. Kindly provide details on the errors you got with Rider in a separate issue. Just noticed they have a free trial, will give it a go but would appreciate if you could provide more details in case the issue isn't Rider specific.

**Comment by markm77** [comment] 2020-08-24 20:01
Hi Jeremy, thanks for your help, appreciated, and sorry for slow response. I did test your change with two debuggers: Rider and VS Code. When not breaking at caught exceptions (only uncaught) both debuggers stop in [eval] losing stack trace. When breaking at caught exceptions both debuggers stop in TypeScript source with full stack trace as before. Shame.

I guess (looking at your PR) you are actually [catching the error](https://github.com/JeringTech/Javascript.NodeJS/pull/88/files#diff-1a4cd5f57e9970e13155ea81adb2223aR189-R194) - hence why the stack trace is lost?

I'll try to log macOS and Rider issues as I can; really struggling with bandwidth right now.

**Comment by JeremyTCD** [comment] 2020-08-25 05:06
Hey Mark, no worries, this is an enhancement so we're in no hurry to resolve it.  

You need to set `NodeJSProcessOptions.CatchUncaughtUserErrors` to `false`. HttpServer.ts will not catch errors:

https://github.com/JeringTech/Javascript.NodeJS/blob/95a452f585d78637e98406a14f46d253b451fb32/src/NodeJS/Javascript/Servers/OutOfProcess/Http/HttpServer.ts#L189-L197

[More info on setting `NodeJSProcessOptions` values](https://github.com/JeringTech/Javascript.NodeJS#configuring-inodejsservice).

**Comment by markm77** [comment] 2020-09-26 12:28
Hi @JeremyTCD , sorry I should have clarified myself earlier. I did check with ```NodeJSProcessOptions.CatchUncaughtUserErrors``` as ```false``` and yes this did cause the code to stop due to the uncaught breakpoint.

The problem is it stops in [eval] with unhelpful stack trace. Which at least for me makes the feature not really useful.

You're right that the code sample you mention (HttpServer.ts) does not ```catch``` this case - but maybe it is being caught somewhere else?

NB: I have just re-checked with Rider 2020.2.3 and behaviour is the same.

**Comment by rjgotten** [comment] 2020-10-26 12:15
The thing with `[eval]` is probably that the Webpacked code ends up built with the `devtool` setting for sourcemaps set to any of the `eval-*` values. These wrap all modules in separate `eval()` calls to inject the source map links.

E.g. https://github.com/webpack/webpack/tree/master/examples/source-map#eval-source-mapjs

Iirc `eval-sourcemaps` is the default for `mode: "development"` which makes me think the conditional logic in webpack.config.js to switch to production builds might not be working as expected.

**Comment by JeremyTCD** [comment] 2021-03-05 08:54
Thanks @rjgotten for the tips. Unfortunately we can't really help with this issue since its IDE-specific. Closing for now.

**Closed by JeremyTCD** 2021-03-05 08:54 UTC
Labels: enhancement
